{
  "nomRequete": "BAI Metro",
  "noRequete": "XW29",
  "codeUtilisateur": "XW29",
  "groupeDevise": [
    {
      "devise": "CAD",
      "listeEntentes": [
        {
          "entente": {
            "_ObjectType": "EntenteParticulier",
            "numeroInstitution": "815",
            "numeroTransit": "20008",
            "numeroEntente": "0102075",
            "comptes": [
              {
                "_ObjectType": "CompteEOP"
              }
            ]
          }
        },
        {
          "entente": {
            "_ObjectType": "EntenteParticulier",
            "numeroInstitution": "815",
            "numeroTransit": "20008",
            "numeroEntente": "0102921",
            "comptes": [
              {
                "_ObjectType": "CompteEOP"
              }
            ]
          }
        },
        {
          "entente": {
            "_ObjectType": "EntenteParticulier",
            "numeroInstitution": "815",
            "numeroTransit": "40025",
            "numeroEntente": "0033271",
            "comptes": [
              {
                "_ObjectType": "CompteEOP"
              }
            ]
          }
        },
        {
          "entente": {
            "_ObjectType": "EntenteParticulier",
            "numeroInstitution": "815",
            "numeroTransit": "40025",
            "numeroEntente": "0033270",
            "comptes": [
              {
                "_ObjectType": "CompteEOP"
              }
            ]
          }
        }
      ]
    }
  ]
},
{
  "nomRequete": "BAI du Matin",
  "noRequete": "XV12_matin",
  "codeUtilisateur": "XW29",
  "groupeDevise": [
    {
      "devise": "CAD",
      "listeEntentes": [
        {
          "entente": {
            "_ObjectType": "EntenteParticulier",
            "numeroInstitution": "815",
            "numeroTransit": "20274",
            "numeroEntente": "0013787",
            "comptes": [
              {
                "_ObjectType": "CompteEOP"
              }
            ]
          }
        },
        {
          "entente": {
            "_ObjectType": "EntenteParticulier",
            "numeroInstitution": "815",
            "numeroTransit": "20274",
            "numeroEntente": "0013787",
            "comptes": [
              {
                "_ObjectType": "CompteEOP"
              }
            ]
          }
        }
      ]
    }
  ]
},
{
  "nomRequete": "BAI du Matin",
  "noRequete": "xy12_matin",
  "filtrePeriode": {
    "_ObjectType": "IntervalleDate",
    "dateDebut": "2019-05-26",
    "dateFin": "2019-06-26"
  },
  "listeEntentes": [
    {
      "_ObjectType": "EntenteParticulier",
      "numeroInstitution": "815",
      "numeroTransit": "20274",
      "numeroEntente": "0013787",
      "comptes": [
        {
          "_ObjectType": "CompteEOP"
        }
      ]
    },
    {
      "_ObjectType": "EntenteParticulier",
      "numeroInstitution": "815",
      "numeroTransit": "20274",
      "numeroEntente": "0013787",
      "comptes": [
        {
          "_ObjectType": "CompteEOP"
        }
      ]
    },
    {
      "_ObjectType": "EntenteParticulier",
      "numeroInstitution": "815",
      "numeroTransit": "20274",
      "numeroEntente": "0013787",
      "comptes": [
        {
          "_ObjectType": "CompteEOP"
        }
      ]
    },
    {
      "_ObjectType": "EntenteParticulier",
      "numeroInstitution": "815",
      "numeroTransit": "20274",
      "numeroEntente": "0013787",
      "comptes": [
        {
          "_ObjectType": "CompteEOP"
        }
      ]
    }
  ]
}
