spring:
  config:
    activate:
      on-profile: xv12_matin
noRequete: XV12_matin
codeUtilisateur: DN29
nomRequete: BAI du Matin
groupeDevise: '{devise=CAD, listeEntentes=[{entente={_ObjectType=EntenteParticulier,
  numeroInstitution=001, numeroTransit=58000, numeroEntente=4700244, comptes=[{_ObjectType=CompteEOP}]}},
  {entente={_ObjectType=EntenteParticulier, numeroInstitution=001, numeroTransit=54700,
  numeroEntente=5400546, comptes=[{_ObjectType=CompteEOP}]}}]}'
