spring:
  config:
    activate:
      on-profile: xy12_matin2
nomRequete: BAI du Matin
noRequete: xy12_matin
filtrePeriode:
  _ObjectType: IntervalleDate
  dateDebut: '2014-02-21'
  dateFin: '2014-08-20'
listeEntentes:
- _ObjectType: EntenteParticulier
  numeroInstitution: '001'
  numeroTransit: '21045'
  numeroEntente: '0012458'
  comptes:
  - _ObjectType: CompteEOP
- _ObjectType: EntenteParticulier
  numeroInstitution: '001'
  numeroTransit: '19002'
  numeroEntente: '1125455'
  comptes:
  - _ObjectType: CompteEOP
- _ObjectType: EntenteParticulier
  numeroInstitution: '815'
  numeroTransit: '20274'
  numeroEntente: '0013787'
  comptes:
  - _ObjectType: CompteEOP
- _ObjectType: EntenteParticulier
  numeroInstitution: '815'
  numeroTransit: '20274'
  numeroEntente: '0013787'
  comptes:
  - _ObjectType: CompteEOP
